vich_uploader:
    db_driver: orm
    metadata:
        type: attribute
    mappings:
        blog:
            uri_prefix: '%env(string:POST_IMAGES_PATH)%'
            upload_destination: '%kernel.project_dir%/assets%env(string:POST_IMAGES_PATH)%'
            #namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            namer: Vich\UploaderBundle\Naming\UniqidNamer
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
